package com.example.demo.gtp.controller;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.gtp.dto.ChatRequest;
import com.example.demo.gtp.service.GeminiService;

@RestController
@RequestMapping("/api/ai")
/*
 * ChatController is a REST controller that handles incoming chat requests and interacts with the GeminiService to generate responses.
 * It exposes an endpoint at /api/ai/ask that accepts POST requests with a ChatRequest payload containing the user's message.
 * The controller then calls the GeminiService to get a response based on the user's message and returns it as a string.
 */
public class ChatController {

    private final GeminiService geminiService;

    public ChatController(GeminiService geminiService) {
        this.geminiService = geminiService;
    }

    /*
    
     * Handles POST requests to the /ask endpoint. It takes a ChatRequest object as input, which contains the user's message.
     * The method calls the GeminiService to get a response based on the user's message and returns it as a string.
     *
     * @param request The ChatRequest object containing the user's message.
     * @return A string response generated by the GeminiService based on the user's message.
     */
    @PostMapping("/ask")
    public String askQuestion(@RequestBody ChatRequest request) {
        return geminiService.getResponse(request.getMessage());
    }
}